dataprep:
    source: F:\data\terms-service\text
    dest: /data/text_datasets/terms_service
    embedding:
        _target_: homelab_rag.models.embeddings.localLlama1B
    is_remote: True
    force_resave: True
